### ISSUE TITLE
isc: `phaseshift_isc` overlaps with `brainiak.utils.phase_randomize`

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#396]
We should not have duplicate functionality.

**Comment by snastase** [comment]
These are not really functional duplicates. I think in theory what we want is (_a_) `phaseshift_isc`, which performs the nonparametric test using phase randomization and returns a null distribution, _p_-values, etc; and (_b_) a more generic `phase_randomize` utility that simply takes in time-series and phase-randomizes them. I think having this `phase_randomize` utility is useful even outside the context of ISC analysis. And ideally, the `phaseshift_isc` function should use the `phase_randomize` function internally. This was a little tricky because the pairwise and leave-one-out ISC approaches apply the phase randomization slightly differently, but should be work now—see #405 (commit [dba670a](https://github.com/brainiak/brainiak/pull/405/commits/dba670a9686841a4232d9867ec440488a20b05eb). I've updated `phaseshift_isc` in `isc`, `utils` and tests to match.

**Comment by mihaic** [comment]
There's a way to close issues with commit messages such that it is clear they were fixed. I think we should use it in the future:
https://help.github.com/articles/closing-issues-using-keywords/
