### ISSUE TITLE
fcma: test_mvpa_voxel_selection fails with scikit-learn 0.22

### ISSUE THREAD

**Issue by mihaic** [brainiak/brainiak#448]
See https://travis-ci.org/brainiak/brainiak/jobs/620219411

Pinning to <0.22 works, but we should fix the underlying issue.

**Comment by CameronTEllis** [comment]
Is anyone working on this? I can take a crack at it if no one else is

**Comment by mihaic** [comment]
It's all yours!

**Comment by mihaic** [comment]
@CameronTEllis, I think it is better to contine the conversation from PR #437 here. Your explanation makes sense; it is likely the length difference is caused by a change in accuracy. Nevertheless, all but one of the accuracy values are the same. Therefore, I think it should be possible to preserve the accuracy value comparison in the test.

**Comment by CameronTEllis** [comment]
Indeed the difference between the results are similar but that is incidental as far as I can tell. Again, I am not sure why the value comparison is the appropriate test because if so it sets an extreme standard that should affect all of our tests. If it is necessary to include this test then we can put in an if statement that deals with this different computation. Other than that I am unsure how to proceed

**Comment by mihaic** [comment]
You are right, we have no standard for tests requiring such comparisons. However, I see no harm keeping this existing test, as long as it is working, and it seems close to working to me.

My proposal, as written in the issue description, is to pin scikit-learn until we figure out what is happening so we can release BrainIAK v0.10.

We can even give ourselves a deadline, let's say version BrainIAK v0.11, and remove the test if we cannot make it work by then.

@yidawang, perhaps you have more insight.

**Comment by CameronTEllis** [comment]
That sounds reasonable then
