### ISSUE TITLE
fmrisim compute_signal_change

### ISSUE THREAD

**Issue by Matthew-Ryan1995** [brainiak/brainiak#481]
Hey,

I have been working through the example for the use of fmrisim found at https://github.com/brainiak/brainiak/blob/master/examples/utils/fmrisim_multivariate_example.ipynb and trying to adapt this to my own example.   I think there might be an error in chunks 46 and 47 when computing `noise_func`.

As it stands, `noise_func` and `signal_func` have different shapes (27 x 294 and 294 x 27 respectively) which is not getting detected by the error check in `compute_signal_change`  (line 3185 in fmrisim.py).  Would I be right in saying that `noise_func` should be transposed so it is of the form **Time x Voxel** ?

I came across this when I was trying to place signal in an example where I had more voxels of interest than time points and I hit an indexing error.

Cheers,
Matt

**Comment by CameronTEllis** [comment]
Hi Matt,

Great catch, thanks for finding this. There is a little bit of a quirk here that I will explain a bit but ultimately you are correct there is an error that needs to be fixed.

So the check I added on line 3185 of fmrisim would catch this, but the current version of BrainIAK that you can download using conda doesn't have that update to the code since it was a relatively recent addition. Hence, it slips through if you run this. 

However, these variables should be the same shape (they didn't use to be in an earlier versions of the code). Hence I have updated the notebook to suit in a new pull request.
